Adding sampler_elemental option to smarty
open-forcefield-group/smarty pull request #142
Opened 2016-09-20 00:06 UTC by camizanette

I am adding the sampler by element type for smarty. I updated the README.md file and cli_smarty.py with some error messages for the new options.

Please, let me know if it is easy to understand the README.md file and any feedback about the new sampler file.

@davidlmobley @bannanc 

Thanks!

2016-09-20 15:14 UTC, davidlmobley commented
I'll try and review today, @camizanette ! Thanks!

2016-09-20 22:49 UTC, davidlmobley commented on README.md
> +We have two sampler options for SMARTY, one if the original and the other is elemental. The principle of sampling is the same, the only change is in which elements we are interesting to look at. Sayi
Grammar/clarity. Probably edit to: "We have two sampler options for SMARTY which differ in how focused the sampling is. The original sampler samples over all elements/patterns at once, whereas the elemental sampler focuses on sampling only one specific element. The principle of sampling is the same; the only change is in which elements we sample over. To sample only over a single element, such as oxygen, for example, we use the elemental sampler to focus on that element. "

2016-09-20 22:49 UTC, davidlmobley commented on README.md
> +Original sampler is the default option. Here, smarty samples around all elements.
Edit: "The original sampler is the default option. Here, smarty samples SMARTS patterns covering all elements contained in the set."

2016-09-20 22:50 UTC, davidlmobley commented on README.md
> +The elemental sampler has the same principle of the original sampler. However, the sampler will occurs for only one element (such as Oxygen, Carbon, Hydrogen, etc), which needs to be specified on the
Edit: "The elemental sampler has the same principles as the original sampler. However, the sampler will sample only a single element (such as Oxygen, Carbon, Hydrogen, etc), which needs to be specified on the command line."

2016-09-20 22:50 UTC, davidlmobley commented on README.md
> +The element number needs to be specified (--element=8 for Oxygen).
"The element number needs to be specified by atomic number (--element=8 for oxygen)."

2016-09-20 22:51 UTC, davidlmobley commented on smarty/atomtyper.py
> +        #for atom in mol.GetAtoms():
Why is this code block commented out now? Should it be?

2016-09-20 22:52 UTC, davidlmobley commented on smarty/cli_smarty.py
> +                      help="If you choose sampler elemental, you have to choose one element to search (number format, such as Oxygen = 8, Carbon = 6 and so on).")
"one element to search (using the atomic number, i.e. --element=8 for oxygen or --elment=6 for carbon, etc.)"

2016-09-20 22:55 UTC, davidlmobley requested changes
Mostly looks good to me, but you need to add at least a minimal test -- i.e. ensure it can get all carbons on AlkEthOH at least if you start with the right answers or something along those lines. Otherwise, there's the risk that someone will make a change which breaks this code and the tests won't tell us. 

I added a few grammar/clarity suggestions for the documentations/examples as well.

2016-09-20 22:56 UTC, davidlmobley commented
@camizanette - comments above.

2016-09-21 04:14 UTC, davidlmobley commented
@camizanette - ping me when you have a test in and we can merge. Thanks.

2016-09-24 16:29 UTC, davidlmobley commented
@camizanette -- your tests are failing; I can't look into why right now, but they'll need to be fixed. Perhaps @bannanc can help.

Also, you need to update to master again.

2016-09-24 16:36 UTC, davidlmobley commented
@camizanette -- looks like your issue for python3.x is this:
```
 File "/home/travis/miniconda/envs/test/lib/python3.4/site-packages/smarty/tests/test_sampler.py", line 3, in <module>
    from smarty import AtomTyper, AtomTypeSampler, AtomTypeSamplerElemental
ImportError: cannot import name 'AtomTypeSamplerElemental'
```
(You can find this by just clicking the red x and scrolling through near the bottom to look at what was an actual error).

In python2.7, you're getting an "!" status rather than an failure symbol; it looks like it is timing out (travis has a time limit on tests). Either the tests you added are just too long, or your test is getting stuck in an infinite loop.

2016-09-25 19:10 UTC, bannanc commented on smarty/cli_smarty.py
> +
This will happen automatically if you use `type = "choice"` instead of "string" in parser.add_option for sampler_type. then also add the parameter `choices = ['original', 'elemental']` to that parser.add_option. 

It's a little cleaner/more efficient.

2016-09-25 22:16 UTC, camizanette commented
@davidlmobley Can you check if it is ok, please?

2016-09-25 22:18 UTC, davidlmobley commented
If @bannanc had time, she can check. I'm on a phone at a soccer game. Otherwise I'll do it late tonight most likely.

2016-09-25 22:19 UTC, davidlmobley commented
Do update to mastet,  though! Can't merge when it needs updating.

2016-09-25 22:37 UTC, bannanc commented
@camizanette is there anything specific you want checked? What code has already been ok'd? I did a quick scan earlier and made a small suggestion to cli_smarty.py. I haven't looked carefully at the sampler_elemental code, but I can if you need a code check.

2016-09-25 22:42 UTC, camizanette commented
@bannanc My priority here is to see if I incorporated all the changes suggested by @davidlmobley, specially the test added on test_sampler.py. Just a final check on my changes to see if they make sense. Thanks!

2016-09-26 01:34 UTC, bannanc commented
Ok, I did a quick look at the test and elemental_sampler. I didn't spend too much time looking at the sampler since it mostly recycles code form smarty. @davidlmobley commented on this before, but there are large chunks of commented code. Those should probably be removed, we can always recover them from old commits here if we need them later. Otherwise I think it's good to go. 

How's it doing? Are you getting 100% anywhere yet?

2016-09-26 03:44 UTC, davidlmobley approved these changes

2016-09-26 03:46 UTC, davidlmobley commented
@camizanette - I think it should be good to go if you've addressed the issues I raised earlier. The tests are passing now as well. Maybe just remove the excess commented code Caitlin mentioned and we can merge?

2016-09-26 18:20 UTC, merged